replicaCount: 2

image:
  repository: 121905340549.dkr.ecr.us-west-2.amazonaws.com/final-project-ecr
  tag: "25-ca20b8b"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

postgresql:
  auth:
    username: postgres
    password: postgres
    database: postgres
  primary:
    persistence:
      storageClass: gp2
      size: 8Gi

env:
  DJANGO_ALLOWED_HOSTS: "*"
  DATABASE_URL: "postgres://postgres:postgres@{{ .Release.Name }}-postgresql:5432/postgres"

envFromSecret: django-app-secret
